"""Concrete config-backed drug response prediction model."""

from __future__ import annotations

import copy
from typing import Any, ClassVar

from drevalpy.models.component_stack import _ComponentStack, build_component_stack
from drevalpy.models.config import ModelConfig, ModelScope
from drevalpy.models.config.resolved import ResolvedModelConfig
from drevalpy.models.mixins._feature_matrix import DRPFeatureMatrixMixin
from drevalpy.models.mixins._hyperparameters import DRPHyperparametersMixin
from drevalpy.models.mixins._logging import _DRPLoggingMixin, _wandb
from drevalpy.models.mixins._persistence import DRPPersistenceMixin
from drevalpy.models.mixins._training import DRPTrainingMixin
from drevalpy.models.tuning.config_resolution import default_config_for_drp_model
from drevalpy.models.tuning.public_flat import config_from_public_hyperparameters, public_hyperparameters_from_config
from drevalpy.models.tuning.search_space import resolve_model_config
from drevalpy.registry.predictor import get as get_predictor


class DRPModel(
    DRPHyperparametersMixin,
    _DRPLoggingMixin,
    DRPPersistenceMixin,
    DRPTrainingMixin,
    DRPFeatureMatrixMixin,
):
    """Experiment-facing drug response model backed by a resolved config.

    Subclasses are generated by ``construct_model``; do not
    subclass directly. Typical lifecycle: instantiate, load features, ``train``,
    ``predict``, then ``save`` / ``load``.

    What is left in this class is the config and identity surface - which
    ``ModelConfig`` the class was built from, what the resolved instance made of
    it, and which views it therefore requires. The behaviour hangs off the mixins:
    ``train`` / ``predict`` in ``mixins/_training.py``, checkpoint I/O in
    ``mixins/_persistence.py``, feature-matrix assembly in
    ``mixins/_feature_matrix.py``, wandb in ``mixins/_logging.py`` and
    hyperparameter resolution in ``mixins/_hyperparameters.py``.
    """

    _model_name: ClassVar[str] = "DRPModel"
    _base_model_config: ClassVar[ModelConfig | None] = None

    def __init__(self, hyperparameters: dict[str, Any] | None = None) -> None:
        """Materialize a fresh component stack from class defaults or flat overrides.

        :param hyperparameters: Optional flat public hyperparameter overrides. ``None`` uses the class default config.
        :raises ValueError: If ``hyperparameters`` cannot be applied to this model class.
        """
        self._init_runtime_fields()

        if hyperparameters is None:
            config = default_config_for_drp_model(type(self))
            if config is None:
                self._apply_model_config(resolve_model_config(self.model_config()))
            else:
                self._apply_model_config(config)
            return
        config = config_from_public_hyperparameters(type(self), hyperparameters)
        if config is None:
            msg = f"Cannot apply hyperparameters for model {self.get_model_name()!r}"
            raise ValueError(msg)
        self._apply_model_config(config)

    def _init_runtime_fields(self) -> None:
        self.wandb_project: str | None = None
        self.wandb_run: Any = None
        self.wandb_config: dict[str, Any] | None = None
        self._in_hyperparameter_tuning = False
        self._stack: _ComponentStack | None = None
        self._empty_training = False
        self._hyperparameters: dict[str, Any] = {}
        self._resolved_model_config: ResolvedModelConfig | None = None

    @classmethod
    def _unmaterialized(cls) -> DRPModel:
        """Return an empty instance without materializing a default stack.

        :returns: Runtime instance with uninitialized stack fields.
        """
        instance = object.__new__(cls)
        instance._init_runtime_fields()
        return instance

    @classmethod
    def _from_resolved_config(cls, config: ModelConfig | ResolvedModelConfig) -> DRPModel:
        """Construct an instance from a template or already-resolved config.

        :param config: Template or resolved model configuration to bind.
        :returns: Instance with stack materialized from ``config``.
        """
        instance = cls._unmaterialized()
        resolved = config if isinstance(config, ResolvedModelConfig) else resolve_model_config(config)
        instance._apply_model_config(resolved)
        return instance

    @classmethod
    def get_model_name(cls) -> str:
        """Return the model identity for this class.

        :returns: Model name bound to the generated class.
        """
        return cls._model_name

    @classmethod
    def model_config(cls) -> ModelConfig:
        """Return a defensive deep copy of the class base config.

        :returns: Deep copy of the ``ModelConfig`` bound to this class.
        :raises RuntimeError: If the class was not produced by ``construct_model``.
        """
        if cls._base_model_config is None:
            msg = f"{cls.__name__} has no base ModelConfig; use construct_model(...)"
            raise RuntimeError(msg)
        return ModelConfig.model_validate(cls._base_model_config.model_dump(mode="python"))

    @classmethod
    def supports_early_stopping(cls) -> bool:
        """Return whether the configured predictor supports early stopping.

        :returns: ``True`` when the predictor exposes early-stopping support.
        """
        predictor_class = get_predictor(cls.model_config().predictor.name)
        return bool(getattr(predictor_class, "supports_early_stopping", False))

    @classmethod
    def is_single_drug(cls) -> bool:
        """Return whether this model is scoped to a single drug.

        :returns: ``True`` when the model scope is single-drug.
        """
        return cls.model_config().scope == ModelScope.SINGLE_DRUG

    @property
    def hyperparameters(self) -> dict[str, Any]:
        """Return a defensive copy of the instance hyperparameters.

        :returns: Copy of flat public hyperparameters for this instance.
        """
        return copy.deepcopy(self._hyperparameters)

    @property
    def early_stopping(self) -> bool:
        """Instance convenience accessor for early-stopping support.

        :returns: ``True`` when the configured predictor supports early stopping.
        """
        return type(self).supports_early_stopping()

    @property
    def is_single_drug_model(self) -> bool:
        """Instance convenience accessor for single-drug scope.

        :returns: ``True`` when this model is scoped to a single drug.
        """
        return type(self).is_single_drug()

    @property
    def cell_line_views(self) -> list[str]:
        """Return required cell-line views derived from the resolved config.

        :returns: Cell-line view names required by the model config.
        """
        if self._resolved_model_config is not None:
            return self._resolved_model_config.cell_line_views()
        return self.model_config().cell_line_views()

    @property
    def drug_views(self) -> list[str]:
        """Return required drug views derived from the resolved config.

        :returns: Drug view names required by the model config.
        """
        if self._resolved_model_config is not None:
            return self._resolved_model_config.drug_views()
        return self.model_config().drug_views()

    def log_hyperparameters(self, hyperparameters: dict[str, Any]) -> None:
        """Store a copy of hyperparameters and optionally log them to wandb.

        :param hyperparameters: Flat public hyperparameters for this instance.
        """
        self._hyperparameters = copy.deepcopy(hyperparameters)
        if not self.is_wandb_enabled():
            return
        if not self._in_hyperparameter_tuning:
            _wandb().config.update({"hyperparameters": self._hyperparameters})

    def _apply_model_config(self, config: ModelConfig | ResolvedModelConfig) -> None:
        resolved = config if isinstance(config, ResolvedModelConfig) else resolve_model_config(config)
        self._resolved_model_config = ResolvedModelConfig.model_validate(resolved.model_dump(mode="python"))
        self.log_hyperparameters(public_hyperparameters_from_config(self._resolved_model_config))
        self._stack = build_component_stack(self._resolved_model_config)
        self._empty_training = False
